config/routes.rb
PiadAPI::Application.routes.draw do
  get "listino_piadine/GetListinoPiadine"

  resources :piadineria
  match 'piadineria/latitudine/:latitudine/longitudine/:longitudine' => 'piadineria#GetPiadinerie', :constraints => {:latitudine => /\-*\d+.\d+/ , :longitudine => /\-*\d+.\d+/ }
  match 'listinoPiadine/:id' => 'listinoPiadine#GetListinoPiadine'

end

app/models/listino_piadine.rb
class ListinoPiadine < ActiveRecord::Base
  belongs_to :piadinerium
  has_many :piadinas
end

app/models/piadina.rb
class Piadina < ActiveRecord::Base
  attr_accessible :ingredienti, :link, :nome, :prezzo, :descrizione
  
  belongs_to :listinoPiadine
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/listino_piadine_controller.rb
class ListinoPiadineController < ApplicationController

  #GET /listinoPiadine/1
  #GET /listinoPiadine/1.json
  def GetListinoPiadine
     
    listino = ListinoPiadine.where("piadineria_id = " + params[:id]).first()
	
	if listino.nil?
		@listinoPiadine = []
	else	
		@listinoPiadine = listino.piadinas
	end
    
    respond_to do |format|
      format.html 
      format.json { render json: @listinoPiadine }
    end
    
  end 
end

app/controllers/piadineria_controller.rb
require 'net/http'

class PiadineriaController < ApplicationController
     
  #GET /piadineria/latitude/1/longitude/1
  #GET /piadineria/latitude/1/longitude/1.json
  def GetPiadinerie
	@piadineria = Piadinerium.all
    @piadineria.each do |piad|
		piad.class.module_eval {attr_accessor :distanza}
		piad.class.module_eval {attr_accessor :tempo}
		
		coordinates= params[:latitudine]+ ',' + params[:longitudine]
		uri = URI('http://maps.googleapis.com/maps/api/directions/json')
        params = { :origin => piad.fullAddress, :destination => coordinates, :sensor => false }
        uri.query = URI.encode_www_form(params)
        res = Net::HTTP.get_response(uri)
		obj = JSON.parse(res.body)
		piad.distanza = obj['routes'][0]['legs'][0]['distance']['text']
		piad.tempo = obj['routes'][0]['legs'][0]['duration']['text']
		@result = obj
		
    end
	@piadineria.sort_by!{|p| p.distanza}	
	respond_to do |format|
	    format.html 
      format.json { render json: @piadineria }
    end
  end
  
  # GET /piadineria
  # GET /piadineria.json
  def index
    @piadineria = Piadinerium.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @piadineria }
    end
  end

  # GET /piadineria/1
  # GET /piadineria/1.json
  def show
    @piadinerium = Piadinerium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @piadinerium }
    end
  end

  # GET /piadineria/new
  # GET /piadineria/new.json
  def new
    @piadinerium = Piadinerium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @piadinerium }
    end
  end

  # GET /piadineria/1/edit
  def edit
    @piadinerium = Piadinerium.find(params[:id])
  end

  # POST /piadineria
  # POST /piadineria.json
  def create
    @piadinerium = Piadinerium.new(params[:piadinerium])

    respond_to do |format|
      if @piadinerium.save
        format.html { redirect_to @piadinerium, notice: 'La piadineria e\' stata creata correttamente.' }
        format.json { render json: @piadinerium, status: :created, location: @piadinerium }
      else
        format.html { render action: "new" }
        format.json { render json: @piadinerium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /piadineria/1
  # PUT /piadineria/1.json
  def update
    @piadinerium = Piadinerium.find(params[:id])

    respond_to do |format|
      if @piadinerium.update_attributes(params[:piadinerium])
        format.html { redirect_to @piadinerium, notice: 'La piadinaria e\' stata aggiornata correttamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @piadinerium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /piadineria/1
  # DELETE /piadineria/1.json
  def destroy
    @piadinerium = Piadinerium.find(params[:id])
    @piadinerium.destroy

    respond_to do |format|
      format.html { redirect_to piadineria_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listino_piadine_helper.rb
module ListinoPiadineHelper
end

app/helpers/listino_piadines_helper.rb
module ListinoPiadinesHelper
end

app/helpers/piadinas_helper.rb
module PiadinasHelper
end

app/helpers/piadineria_helper.rb
module PiadineriaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PiadAPI</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listino_piadine/GetListinoPiadine.html.erb
<h1>Listino piadine</h1>

<% if @listinoPiadine.empty? %>
	Nessun listino inserito

<% else %>
		<table>
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Ingredienti</th>
				<th>Link</th>
				<th>Prezzo</th>
				<th>Descrizione</th>    
			</tr>


			<% @listinoPiadine.each do |piadina| %>
			<tr>
				<td><%= piadina.id %></td>
				<td><%= piadina.nome %></td>
				<td><%= piadina.ingredienti %></td>
				<td><%= piadina.link %></td>
				<td><%= piadina.prezzo %></td>  
				<td><%= piadina.descrizione %></td>
			</tr>
		<% end %>

<% end %>

</table>

app/views/piadineria/GetListinoPiadine.html.erb
<h1>Listing piadineria</h1>

<table>
  <tr>
  	<th>ID</th>
    <th>Nome</th>
    <th>Ingredienti</th>
    <th>Link</th>
    <th>Prezzo</th>
    <th>Descrizione</th>    
  </tr>
   

<% @listinoPiadine.each do |piadina| %>
  <tr>
  	<td><%= piadina.id %></td>
    <td><%= piadina.nome %></td>
    <td><%= piadina.ingredienti %></td>
    <td><%= piadina.link %></td>
    <td><%= piadina.prezzo %></td>  
    <td><%= piadina.descrizione %></td>
  </tr>
<% end %>
</table>

app/views/piadineria/GetPiadinerie.html.erb
<h1>Elenco piadinerie</h1>

<table>
  <tr>
    <th>Ragione sociale</th>
    <th>Indirizzo</th>
    <th>Comune</th>
    <th>Provincia</th>
    <th>Regione</th>
    <th>Latitudine</th>
    <th>Longitudine</th>
    <th>Distanza</th>
    <th>Tempo</th>
  </tr>

<% @piadineria.each do |piadinerium| %>
  <tr>
    <td><%= piadinerium.ragioneSociale %></td>
    <td><%= piadinerium.address %></td>
    <td><%= piadinerium.city %></td>
    <td><%= piadinerium.province %></td>
    <td><%= piadinerium.region %></td>
    <td><%= piadinerium.latitude %></td>
    <td><%= piadinerium.longitude %></td>
	<td><%= piadinerium.distanza %></td>
	<td><%= piadinerium.tempo %></td>
  </tr>
<% end %>
</table>

<br/>
<%= link_to 'Indietro', piadineria_path %>

app/views/piadineria/_form.html.erb
<%= form_for(@piadinerium) do |f| %>
  <% if @piadinerium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@piadinerium.errors.count, "error") %> prohibited this piadinerium from being saved:</h2>

      <ul>
      <% @piadinerium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Ragione sociale <br />
    <%= f.text_field :ragioneSociale %>
  </div>
  <div class="field">
    Indirizzo <br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    Comune <br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    Provincia <br />
    <%= f.text_field :province %>
  </div>
  <div class="field">
    Regione <br />
    <%= f.text_field :region %>
  </div>
  <div class="field">
    Latitudine <br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    Longitudine <br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/piadineria/edit.html.erb
<h1>Piadineria</h1>

<%= render 'form' %>

<%= link_to 'Dettaglio', @piadinerium %> |
<%= link_to 'Indietro', piadineria_path %>

app/views/piadineria/index.html.erb
<br />
<br />
<h1>Elenco piadinerie</h1>

<table class="table table-hover">
  <tr>
    <th>Ragione sociale</th>
    <th>Indirizzo</th>
    <th>Comune</th>
    <th>Provincia</th>
    <th>Regione</th>
    <th>Latitudine</th>
    <th>Longitudine</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @piadineria.each do |piadinerium| %>
  <tr>
    <td><%= piadinerium.ragioneSociale %></td>
    <td><%= piadinerium.address %></td>
    <td><%= piadinerium.city %></td>
    <td><%= piadinerium.province %></td>
    <td><%= piadinerium.region %></td>
    <td><%= piadinerium.latitude %></td>
    <td><%= piadinerium.longitude %></td>
    <td><%= link_to 'Dettaglio', piadinerium %></td>
    <td><%= link_to 'Modifica', edit_piadinerium_path(piadinerium) %></td>
    <td><%= link_to 'Elimina', piadinerium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Aggiungi', new_piadinerium_path %>

app/views/piadineria/new.html.erb
<h1>Piadineria</h1>

<%= render 'form' %>

<%= link_to 'Indietro', piadineria_path %>

app/views/piadineria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ragione sociale:</b>
  <%= @piadinerium.ragioneSociale %>
</p>

<p>
  <b>Indirizzo:</b>
  <%= @piadinerium.address %>
</p>

<p>
  <b>Comune:</b>
  <%= @piadinerium.city %>
</p>

<p>
  <b>Provincia:</b>
  <%= @piadinerium.province %>
</p>

<p>
  <b>Regione:</b>
  <%= @piadinerium.region %>
</p>

<p>
  <b>Latitudine:</b>
  <%= @piadinerium.latitude %>
</p>

<p>
  <b>Longitudine:</b>
  <%= @piadinerium.longitude %>
</p>


<%= link_to 'Modifica', edit_piadinerium_path(@piadinerium) %> |
<%= link_to 'Indietro', piadineria_path %>